env:
  github_token: "ENCRYPTED[!e54eb99577b2251f1b956656905bb4f59a561b3f1412584ad86922e6de981ec5f2f5e87c2ec45812a14005883636fc01!]"
  rclone_config: "ENCRYPTED[!d539ab513a653c9ce419c6f2b5309bdeec2760bf8f92511563a91df3c24c11252989295c8b71b90e5d5ac9395e6b2290!]"
  telegram_bot_token: "ENCRYPTED[!f1d6be2955abc0e707d19e911e742d164c53d4abd3136d5cda5bc0c25a09e9a7f8668ea263e382612f3f8de8f51a6413!]"
  telegram_id_channel: "ENCRYPTED[!01678c0ad198e91ae46a395b924f8e85126dde9da25262b7bff06b8ab3f6cac5c4c30399d6068da813664c8343fb5765!]"

task:
  name: "test script"
  timeout_in: 120m
  container:
    image: accupara/ubuntu:22.04
    cpu: 8
    memory: 32G

  Build-Env-Setup_background_script:
    - export DEBIAN_FRONTEND=noninteractive
    - mkdir -p ~/.config/rclone
    - echo "$rclone_config" > ~/.rclone.conf
    - git config --global user.name "Shravan55555"
    - git config --global user.email "srasidda.ks@gmail.com"
    - echo "$github_token" > ~/.git-credentials
    - git config --global credential.helper store --file=~/.git-credentials
    - rm -rf ~/ccache
    - mkdir -p ~/ccache
    - rclone copy RMX1901:AppDrive/ccache.tar.gz ~/ -P
    - cd ~/
    - time tar xf ccache.tar.gz
    - cd ~/

  Storage-Checker_background_script:
    - df -h
    - lsblk
    - ls -l -a -h
    - ./sleep.sh

  Sync_script:
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Starting sync RisingTechOSS source...."
    - rm -rf ~/rom
    - mkdir -p ~/rom
    - cd ~/rom
    - rm -rf * .repo
    - repo init -u https://gitlab.com/ThankYouHonami/manifest.git -b fourteen -g default,-mips,-darwin,-notdefault
    - git clone https://github.com/Shravan55555/local_manifest.git -b main .repo/local_manifests
    - repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Sync RisingTechOSS source completed!"

  Build_script:
    - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Build RisingTechOSS started...."
    - ./final.sh
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Build $(cd ~/rom/out/target/product/RMX1901/ && ls rising_*.zip) completed!"
    - ./collect.sh
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Compressing ccache...."

  Upload_script:
    - ./compressing.sh
    - cd ~/
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Uploading ccache...."
    - rclone copy ccache.tar.gz RMX1901:AppDrive -P
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Ccache RisingTechOSS uploaded successfully!"
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Uploading build...."
    - rclone copy ~/rom/out/target/product/RMX1901/rising_*.zip RMX1901:ROM -P
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Build $(cd ~/rom/out/target/product/RMX1901/ && ls rising_*.zip) uploaded successfully!"
 
