env:
  github_token: "ENCRYPTED[2e3323abdd6505939e2c384b97342574aa96454b62ef40e68e8bd6163da7fc37c8780b1025a984fb40fc665f37c1b2b4]"
  rclone_config: "ENCRYPTED[!d539ab513a653c9ce419c6f2b5309bdeec2760bf8f92511563a91df3c24c11252989295c8b71b90e5d5ac9395e6b2290]"
  telegram_bot_token: "ENCRYPTED[]"
  telegram_id_channel: "ENCRYPTED[]"

task:
  name: "test script"
  timeout_in: 120m
  container:
    image: inok2341/anu:latest
    cpu: 8
    memory: 32G

  Build-Env-Setup_background_script:
    - export DEBIAN_FRONTEND=noninteractive
    - mkdir -p ~/.config/rclone
    - echo "$rclone_config" > ~/.rclone.conf
    - git config --global user.name "Shravan55555"
    - git config --global user.email "srasidda.ks@gmail.com"
    - echo "$github_token" > ~/.git-credentials
    - git config --global credential.helper store --file=~/.git-credentials
    - rm -rf ~/ccache
    - mkdir -p ~/ccache
    - rclone copy RMX1901:AppDrive/ccache.tar.gz ~/ -P
    - cd ~/
    - time tar xf ccache.tar.gz
    - cd ~/

  Storage-Checker_background_script:
    - df -h
    - lsblk
    - ls -l -a -h
    - ./sleep.sh

  Sync_script:
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Starting sync NusantaraOS Android 11 source...."
    - rm -rf ~/rom
    - mkdir -p ~/rom
    - cd ~/rom
    - rm -rf * .repo
    - repo init --depth=1 --no-repo-verify -u https://github.com/RisingTechOSS/android -b thirteen -g default,-mips,-darwin,-notdefault
    - git clone https://github.com/Shravan55555/local_manifest --depth 1 -b main .repo/local_manifests
    - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Sync NusantaraOS Android 11 source completed!"

  Build_script:
    - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Build NusantaraOS Android 11 started...."
    - ./final.sh
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Build $(cd ~/rom/out/target/product/juice/ && ls Nusantara_*.zip) completed!"
    - ./collect.sh
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Compressing ccache...."

  Upload_script:
    - ./compressing.sh
    - cd ~/
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Uploading ccache...."
    - rclone copy ccache.tar.gz RMX1901:AppDrive -P
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Ccache NusantaraOS Android 11 uploaded successfully!"
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Uploading build...."
    - rclone copy ~/rom/out/target/product/RMX1901/rising_*.zip RMX1901:ROM -P
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Build $(cd ~/rom/out/target/product/juice/ && ls Nusantara_*.zip) uploaded successfully!"
 
